#!/usr/bin/env python
# coding: utf-8

# In[ ]:


import numpy as np
import pandas as pd
from scipy.optimize import curve_fit
from scipy import stats as statistics
from statsmodels.stats.multitest import fdrcorrection

# define functions needed for threshold simulation
def func(x, a, b):
    return a * np.exp(-b * x)

def rsquared (x, y):
    slope, intercept, r_value, p_value, stderr = statistics.linregress(x, y)
    return r_value ** 2

# define functions to calculate threshold, foldbetter, qvalue filter columns, sig core genes
def qvalue_filter(row):
    if row['fdr_q_value_core_pathway'] < 0.05:
        return 1
    else:
        return 0

def threshold(row, a, b, threshold_dictionary):
    if int(row['functional_group_size']) <= 15 and int(row['functional_group_size']) >= 5: #modified for removing smaller pathway simulations
        thresh = threshold_dictionary[int(row['functional_group_size'])]
        return thresh
    else:
        thresh = func(float(row['functional_group_size']), a, b)
        return thresh

def foldbetter(row):
    fold_better = row['5th_percentile_threshold']/row['core_group_pvalue']
    return fold_better

def collect_core_genes_in_sig_groups(summary_matrix):
    significant_core_genes = []
    for row in range(summary_matrix.shape[0]):
        row_q_value_filter = summary_matrix.at[row, 'passed_q_value_filter']
        row_foldbetter = summary_matrix.at[row, 'fold_better']
        
        if row_q_value_filter == 1 and row_foldbetter > 1:
            row_core_genes = [summary_matrix.at[row, 'core_genes']]
            significant_core_genes.extend(row_core_genes)
    
    significant_core_genes = [item for sublist in significant_core_genes for item in sublist]
    significant_core_genes_set = set(significant_core_genes)
    
    return significant_core_genes_set

# function comparing true data to simulated data
def compare_to_simulations(small_and_large_sims_lst, sim_percentile_matrix, summary_matrix):
    # collect 5th percentile p-values from simulations for threshold calculation
    xvalues = small_and_large_sims_lst
    yvalues = list(sim_percentile_matrix[5])
    xvalues = [float(x) for x in xvalues]
    yvalues = [float(x) for x in yvalues]

    # create threshold_dictionary to call exact threshold values for pathways <= 15
    threshold_dictionary = dict(zip(xvalues, yvalues))

    # calculate coefficients for func that was previously defined using x and y values
    x = np.array(xvalues)
    y = np.array(yvalues)
    popt, pcov = curve_fit(func, x, y, [0.2, 0.2])
    print('threshold=' + str(popt[0]) + '*EXP(-' + str(popt[1]) + '*OriginalGroupSize)')
    a = popt[0]
    b = popt[1]

    # calculate r-squared for ln transformed data
    # r-squared is generated by transforming data by natural log to make linear
    # but, actual data is fit to exponential curve and threshold is derived from expoential fitted data
    # should x undergo ln too? check without...
    ln_x = [np.log(i) for i in x]
    ln_y = [np.log(i) for i in y]
    print('r-squared for this equation is: ' + str(rsquared(x, y)))
    
    # had to generate extra steps for fdr correction because i set p-value = 1 for groups with no mutations
    # groups without mutations are removed prior to fdr correction
    # also, noticed that AK code is missing some of the communities...don't know what is happening
    # this is going to generate different q-values, unless i can determine location of discrepency

    # fdr correction of true sample data
    summary_matrix_fdr = summary_matrix.copy()
    summary_matrix_fdr = summary_matrix_fdr[~summary_matrix_fdr['core_genes'].apply(lambda x: 'No nonsyn SNV mutations in biological group' in x)]
    sample_core_group_pvalues = tuple(summary_matrix_fdr['core_group_pvalue'])
    fdr_core_group_pvalues = fdrcorrection(sample_core_group_pvalues, alpha = 0.05)[1]
    summary_matrix_fdr['fdr_q_value_core_pathway'] = fdr_core_group_pvalues
    summary_matrix = summary_matrix.merge(summary_matrix_fdr[['group_name', 'fdr_q_value_core_pathway']], on="group_name", how="outer")

    # compare true sample data to simulations and add to summary_matrix
    summary_matrix['passed_q_value_filter'] = summary_matrix.apply (lambda row: qvalue_filter(row), axis=1)
    summary_matrix['5th_percentile_threshold'] = summary_matrix.apply (lambda row: threshold(row, a, b, threshold_dictionary), axis=1)
    summary_matrix['fold_better'] = summary_matrix.apply (lambda row: foldbetter(row), axis=1)
    summary_matrix.sort_values(by = ['passed_q_value_filter', 'fold_better'], ascending = False, inplace = True)
    
    return summary_matrix

